attributes:
  axes: !!python/tuple
  - z
  - y
  - x
  offset: !!python/tuple
  - 0
  - 0
  - 0
  resolution: !!python/tuple
  - 1
  - 1
  - 1
output_zarr_path: data/name/train
path_to_gt_PC_neg_tiff_train: ''
path_to_gt_PC_neg_tiff_validate: ''
path_to_gt_PC_pos_tiff_train: ''
path_to_gt_PC_pos_tiff_validate: ''
path_to_raw_tiff_train: ''
path_to_raw_tiff_validate: ''
