attributes:
  axes: !!python/tuple
  - z
  - y
  - x
  offset: !!python/tuple
  - 0
  - 0
  - 0
  resolution: !!python/tuple
  - 60
  - 60
  - 60
output_zarr_path: data/19-13_validation.zarr
path_to_gt_PC_neg_tiff_train: 'data/TIF_data/19-13_ground_truth/gt_neg'
path_to_gt_PC_neg_tiff_validate: 'data/TIF_data/19-13_ground_truth/gt_neg'
path_to_gt_PC_pos_tiff_train: 'data/TIF_data/19-13_ground_truth/gt_pos'
path_to_gt_PC_pos_tiff_validate: 'data/TIF_data/19-13_ground_truth/gt_pos'
path_to_raw_tiff_train: 'data/TIF_data/19-13_ground_truth/raw'
path_to_raw_tiff_validate: 'data/TIF_data/19-13_ground_truth/raw'
